title: "Hello World"
layout: "sidebar"
components:
    - type: "section"
      className: "flex flex-col items-center justify-center min-h-screen gap-6"
      children:
          - type: "h1"
            className: "text-4xl font-bold text-blue-600 font-bold underline"
            content: "Welcome to Randamu's Playground"
          - type: "p"
            className: "text-lg text-gray-600 mb-4"
            content: "This is a demonstration of our component system"
          - type: "Button"
            props:
                text: "Click me!"
                variant: "primary"
                size: "lg"
                className: "animate-bounce"
          - type: "Button"
            props:
                text: "Secondary Action"
                variant: "secondary"
                size: "md"
                className: "mt-4"
