default:
    container:
        className: "min-h-screen bg-gray-50"
    main:
        className: "container mx-auto px-4"

centered:
    container:
        className: "min-h-screen bg-white flex items-center justify-center"
    main:
        className: "w-full max-w-4xl px-4"

sidebar:
    container:
        className: "min-h-screen bg-gray-100 flex"
    sidebar:
        className: "w-64 bg-white shadow-lg"
    main:
        className: "flex-1 p-8"
